<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Google_Classroom</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Week 1\Day 1\Practice Problem 1\" />
    <Folder Include="Week 1\Day 1\Practice Problem 2\" />
    <Folder Include="Week 1\Day 1\Practice Problem 3\" />
    <Folder Include="Week 1\Day 2\02 C# Control Flow Level 1 Lab Practice\" />
    <Folder Include="Week 1\Day 2\03 C# Control Flow Level 2 Lab Practice\" />
    <Folder Include="Week 1\Day 2\04 C# Control Flow Level 3 Lab Practice\" />
    <Folder Include="Week 1\Day 2\02 C# Arrays Level 1 Lab Practice\" />
    <Folder Include="Week 1\Day 2\03 C# Arrays Level 2 Lab Practice\" />
    <Folder Include="Week 1\Day 3\02 C# Methods Level 1 Practice Programs\" />
    <Folder Include="Week 1\Day 3\03 C# Methods Level 2 Practice Programs\" />
    <Folder Include="Week 1\Day 3\04 C# Methods Level 3 Practice Programs\" />
    <Folder Include="Week 1\Day 4\Day 8 Problem Statement\" />
    <Folder Include="Week 1\Day 5\Problem Statements for Practice\" />
    <Folder Include="Week 1\Day 5\Problem Statment\" />
  </ItemGroup>

</Project>
