<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Google_Classroom</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Week 1\Day 1\Practice Problem 1\" />
    <Folder Include="Week 1\Day 1\Practice Problem 2\" />
    <Folder Include="Week 1\Day 1\Practice Problem 3\" />
    <Folder Include="Week 1\Day 2\02 C# Control Flow Level 1 Lab Practice\" />
    <Folder Include="Week 1\Day 2\03 C# Control Flow Level 2 Lab Practice\" />
    <Folder Include="Week 1\Day 2\04 C# Control Flow Level 3 Lab Practice\" />
    <Folder Include="Week 1\Day 2\02 C# Arrays Level 1 Lab Practice\" />
    <Folder Include="Week 1\Day 2\03 C# Arrays Level 2 Lab Practice\" />
    <Folder Include="Week 1\Day 3\02 C# Methods Level 1 Practice Programs\" />
    <Folder Include="Week 1\Day 3\03 C# Methods Level 2 Practice Programs\" />
    <Folder Include="Week 1\Day 3\04 C# Methods Level 3 Practice Programs\" />
    <Folder Include="Week 1\Day 4\Day 8 Problem Statement\" />
    <Folder Include="Week 1\Day 5\Problem Statements for Practice\" />
    <Folder Include="Week 1\Day 5\Problem Statment\" />
    <Folder Include="Week 1\Day 6\01 Java Class and Object Level 1 Lab Practice\" />
    <Folder Include="Week 1\Day 7\02 Java Constructors, Instance vs. Class Variables, Access Modifiers Level 1 Lab Practice\" />
    <Folder Include="Week 1\Day 7\03 this, sealed, static key words and is Operator Level 1 Lab Practice\" />
    <Folder Include="Week 2\Day 1\Sajal Gupta - Submission of Inheritance\" />
    <Folder Include="Week 2\Day 2\06 Submission of Encapsulation, Polymorphism, Interface and Abstract Class\" />
    <Folder Include="Week 2\Day 3\05 Submission of NUnit\Actual Work\" />
    <Folder Include="Week 2\Day 3\05 Submission of NUnit\Testing\" />
    <Folder Include="Week 2\Day 3\05 Submission of Regex\" />
    <Folder Include="Week 2\Day 4\01 - Submission of C# Generics\" />
    <Folder Include="Week 3\Day 1\02 Submission of Collections\" />
    <Folder Include="Week 3\Day 2\Submission of Data Structure - LinkedList\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="4.6.1" />
  </ItemGroup>

</Project>
